### PR TITLE
beta adaptive icon

### PR DESCRIPTION
**Pull request by splendidbits**

### CODE REVIEW

**Comment by wight554** [comment]
imo that outline style looks more like icon for some iconpack
or I have a bad taste idk

**Comment by MSF-Jarvis** [comment]
Looking at the icon on my homescreen I kinda have to agree with @wight554, this does __not__ look good as an application icon because it stands out in stark contrast with everything else I have on my phone. All the people I've shown the icon to have told me they want the ability to use the old icon should I choose to merge this PR, and that does not bode well for this change.

**Comment by splendidbits** [comment]
I agree. It looks completely different on a phone - it doesn't scale well. Back to the drawing board :)

**Comment by MSF-Jarvis** [comment]
@splendidbits No I'm not fixated on any colors, the burgundy from the original logo can very well go. The app is pretty much an independent project with its own set of features and an arguably better UI, but I've retained the name to reflect the original goal of why I started with this as well as retaining a slight brand identification for newcomers to recognize the utility of the application.

**Pull request closed without merging**
