### PR TITLE
Apply 'Lato' font to the UI

### PR DESCRIPTION
**Pull request by MSF-Jarvis**
I'm not set on this font or even the whole idea in general so this PR
is your shot at letting me know of better looking fonts (I didn't look too
deeply, Google Fonts has just too many of them >.<) or if you'd prefer the
app just stay the fuck out of the fonts business and let you use your
Comic Sans everywhere.

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
Test this at [WireGuard-KT-78-63c33371cc6a6c10fcd471059b322bba9ddeae8f.apk](https://transfer.sh/yGgDL/WireGuard-KT-78-63c33371cc6a6c10fcd471059b322bba9ddeae8f.apk).



 _This is an automatically posted message from Travis-CI_

**Comment by kdrag0n** [comment]
Please don't force a font upon the user. If you want to use Actor, apply that system-wide on your device. It's annoying when users apply fonts that they expect to effect every app but end up with apps like this that don't respect the font and use their own.

**Comment by MSF-Jarvis** [comment]
> Please don't force a font upon the user. If you want to use Actor, apply that system-wide on your device. It's annoying when users apply fonts that they expect to effect every app but end up with apps like this that don't respect the font and use their own.

Typography is as important to an application's design as its colour scheme. As I said, I'm not super bent on having a custom font used, but even when I do, this is not being "forced" on the user, users signed up for all my design choices when they started using the app :stuck_out_tongue:. About the whole "apps don't respect my Comic Sans", apps don't respect your customised system accents on things like OnePlus' OxygenOS either, the design goal here is consistency across all random OEM ROMs, and not blending in with their ugliness.

**Comment by MSF-Jarvis** [comment]
Test this at [WireGuard-KT-78-33a25ae0a9ac8da913fc55a46ac4f039e072d556.apk](https://transfer.sh/qkR7g/WireGuard-KT-78-33a25ae0a9ac8da913fc55a46ac4f039e072d556.apk).



 _This is an automatically posted message from Travis-CI_

**Comment by MSF-Jarvis** [comment]
Test this at [WireGuard-KT-78-4dc28ba20c76775c5bfe926eb43d7515e51f3238.apk](https://transfer.sh/TiQnp/WireGuard-KT-78-4dc28ba20c76775c5bfe926eb43d7515e51f3238.apk).



 _This is an automatically posted message from Travis-CI_

**Comment by kdrag0n** [comment]
> > Please don't force a font upon the user. If you want to use Actor, apply that system-wide on your device. It's annoying when users apply fonts that they expect to effect every app but end up with apps like this that don't respect the font and use their own.
> 
> Typography is as important to an application's design as its colour scheme. As I said, I'm not super bent on having a custom font used, but even when I do, this is not being "forced" on the user, users signed up for all my design choices when they started using the app stuck_out_tongue. About the whole "apps don't respect my Comic Sans", apps don't respect your customised system accents on things like OnePlus' OxygenOS either, the design goal here is consistency across all random OEM ROMs, and not blending in with their ugliness.

That's like saying every app has its own font. Sure, they may use them for emphasis, but not for most of the UI. There are only a few select apps I know that do this: Telegram, Telegram X, Discord, and Spotify. I am not a fan of any of these, and have made Substratum overlays just to change the font of Discord. It's tedious to do this for every app that violates the system-wide settings.

And at least, if you're going to use a custom font, include the font in the app so it's independent. There's a visible delay between first installing the custom fonted app and the font applying. Instead of depending on GMS for such a basic thing, include the .otf file in the APK. Pick a nicer font as well. Some that come to mind are Noto Sans and Lato.

One other thing that comes to mind is people who use custom fonts for readability. Custom fonts that don't meet their standards might end up being hard to read. That doesn't help retention or the user.

**Comment by MSF-Jarvis** [comment]
> > > Please don't force a font upon the user. If you want to use Actor, apply that system-wide on your device. It's annoying when users apply fonts that they expect to effect every app but end up with apps like this that don't respect the font and use their own.
> > 
> > 
> > Typography is as important to an application's design as its colour scheme. As I said, I'm not super bent on having a custom font used, but even when I do, this is not being "forced" on the user, users signed up for all my design choices when they started using the app stuck_out_tongue. About the whole "apps don't respect my Comic Sans", apps don't respect your customised system accents on things like OnePlus' OxygenOS either, the design goal here is consistency across all random OEM ROMs, and not blending in with their ugliness.
> 
> That's like saying every app has its own font. Sure, they may use them for emphasis, but not for most of the UI. There are only a few select apps I know that do this: Telegram, Telegram X, Discord, and Spotify. I am not a fan of any of these, and have made Substratum overlays just to change the font of Discord. It's tedious to do this for every app that violates the system-wide settings.
> 
> And at least, if you're going to use a custom font, include the font in the app so it's independent. There's a visible delay between first installing the custom fonted app and the font applying. Instead of depending on GMS for such a basic thing, include the .otf file in the APK. Pick a nicer font as well. Some that come to mind are Noto Sans and Lato.

300ms delay at worst. Anyways, moved to bundling the font and switched to Lato.

> One other thing that comes to mind is people who use custom fonts for readability. Custom fonts that don't meet their standards might end up being hard to read. That doesn't help retention or the user.

**Comment by MSF-Jarvis** [comment]
Test this at [WireGuard-KT-78-fa1a3518882820fe431c3472ca01a7843b628a57.apk](https://transfer.sh/10xtbl/WireGuard-KT-78-fa1a3518882820fe431c3472ca01a7843b628a57.apk).



 _This is an automatically posted message from Travis-CI_

**Comment by MSF-Jarvis** [comment]
Test this at [WireGuard-KT-78-b5090227bc96d73a024a350635d9c79a439b6f0e.apk](https://transfer.sh/TD4K0/WireGuard-KT-78-b5090227bc96d73a024a350635d9c79a439b6f0e.apk).



 _This is an automatically posted message from Travis-CI_

**Pull request merged**
